#!/bin/bash
#
# Documentation of tools/print_config.py
# https://mmclassification.readthedocs.io/en/latest/tools/miscellaneous.html#print-the-entire-config

python /mmclassification/tools/misc/print_config.py "$@"
